fix yaml string

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -26,7 +26,8 @@ jobs:
     - name: Install yq
       run: apt install yq
     - name: Check versions are consistent
-      run: [ "$(tomlq -r '.package.version' cbr-wasm/Cargo.toml)" = "$(tomlq -r '.dependencies."challenge-bypass-ristretto".version' cbr-wasm/Cargo.toml)" ] || (echo "Error: Crate version does not match challenge-bypass-ristretto version" && exit 1)
+      run: |
+        [ "$(tomlq -r '.package.version' cbr-wasm/Cargo.toml)" = "$(tomlq -r '.dependencies."challenge-bypass-ristretto".version' cbr-wasm/Cargo.toml)" ] || (echo "Error: Crate version does not match challenge-bypass-ristretto version" && exit 1)
     - name: Check formatting
       run: cargo fmt --check
     - name: Install wasm target and wasm-pack
